# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

target 'IntegrationIOS' do 

pod 'AFNetworking', '~> 2.6'
 
end
             
target 'IntegrationIOSTests' do
    
pod 'AFNetworking', '~> 2.6'
pod 'Specta'
pod 'Expecta'
pod 'OCMock'

end
